

services:

  main_app:
    build:
      context: .

    depends_on:
      - db

    ports:
      - 8000:8000

    env_file:
      - .env

    volumes:
      - .:/src
    command: >
      sh -c "alembic upgrade head && uvicorn --factory app.application.main:create_app --reload --host 0.0.0.0 --port 8000"
      

  db:
    image: postgres:16.3-alpine
    restart: always
    env_file:
      - .env

    volumes:
      - volume:/var/lib/postgresql

volumes:
  volume: