

services:

  main_app:
    build:
      context: .

    ports:
      - 8000:8000

    env_file:
      - .env

    volumes:
      - .:/src
    command: >
      sh -c "uvicorn --factory app.application.main:create_app --reload --host 0.0.0.0 --port 8000"