"""Edit models

Revision ID: 18ffb526e850
Revises: 567ca8b03b5b
Create Date: 2024-10-01 12:01:00.646612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18ffb526e850'
down_revision: Union[str, None] = '567ca8b03b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Breed', 'size')
    op.drop_column('Breed', 'activity')
    op.add_column('Cat', sa.Column('breed_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Cat', 'Breed', ['breed_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Cat', type_='foreignkey')
    op.drop_column('Cat', 'breed_id')
    op.add_column('Breed', sa.Column('activity', postgresql.ENUM('active', 'inactive', name='activity'), autoincrement=False, nullable=False))
    op.add_column('Breed', sa.Column('size', postgresql.ENUM('small', 'average', 'big', name='size'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
