"""Create Base models

Revision ID: 567ca8b03b5b
Revises: 
Create Date: 2024-10-01 11:40:28.603095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567ca8b03b5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Breed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('size', sa.Enum('small', 'average', 'big', name='size'), nullable=False),
    sa.Column('activity', sa.Enum('active', 'inactive', name='activity'), nullable=False),
    sa.CheckConstraint('length(name) <= 255', name='check_name_max_length'),
    sa.CheckConstraint('length(name) > 0', name='check_name_min_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Cat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.Enum('white', 'gray', 'black', 'ginger', name='color'), nullable=False),
    sa.Column('age_in_month', sa.Integer(), nullable=False),
    sa.CheckConstraint('age_in_month > 0', name='check_age_in_month_min_value'),
    sa.CheckConstraint('length(name) <= 255', name='check_name_max_length'),
    sa.CheckConstraint('length(name) > 0', name='check_name_min_length'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Cat')
    op.drop_table('Breed')
    # ### end Alembic commands ###
